[package]
name = "owl-recorder"
version = "0.8.0"
edition = "2024"

[dependencies]
raw-input.workspace = true
game-process.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tokio-util.workspace = true
color-eyre.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri-winrt-notification.workspace = true
sysinfo.workspace = true
libobs-wrapper.workspace = true
libobs-sources.workspace = true
libobs-window-helper.workspace = true
async-trait.workspace = true
windows.workspace = true

anyhow = "1.0" # Used just by the bootstrapper

constants = { path = "../constants" }