name: Build and Release

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
          components: rustfmt, clippy

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check Rust formatting
        run: cargo fmt -- --check

      - name: Check Rust with Clippy
        run: cargo clippy -- -D warnings

      - name: Check Python formatting
        run: uv run ruff format --check

      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.1
        with:
          nsis-version: "3.10"

      - name: Run build script
        shell: powershell
        run: .\build-resources\scripts\build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: owl-control-windows-x64
          path: |
            dist/OWL Control.exe
            dist/resources/**/*

      - name: Upload installer
        uses: actions/upload-artifact@v4
        if: hashFiles('dist/*.exe') != ''
        with:
          name: owl-control-installer-windows
          path: "dist/*.exe"

  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: |
          echo "=== All artifacts ==="
          ls -la artifacts/
          echo "=== Contents of each artifact ==="
          find artifacts -type f -name "*.exe" -o -name "*.zip" | head -20

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/OWL Control Setup*
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
